---

- hosts: nodes
  vars:
    src_yaml_file: "./files/test.yaml"
    dst_yaml_file: "/root/test.yaml"
    src_json_file: "./files/test.json"
    dst_json_file: "/root/test.json"
  tasks:
    - name: "Copy some 'local facts' to the server"
      copy:
        src: "{{ src_json_file }}"
        dest: "{{ dst_json_file }}"
    - name: "Copy some 'config' to the server"
      copy:
        src: "{{ src_yaml_file }}"
        dest: "{{ dst_yaml_file }}"
    - set_fact:
        new_label_dict: "{{ hostvars[inventory_hostname].node_labels }}"
    - set_fact:
        new_label_list: "{{ new_label_dict | dict_to_kv_list }}"
    - modify_yaml:
        yaml_key: "kubeletArguments.node-labels"
        yaml_value: "{{ new_label_list }}"
        dest: "{{ dst_yaml_file }}"
    - modify_json:
        json_key: "node.labels"
        json_value: "{{ new_label_dict }}"
        dest: "{{ dst_json_file }}"
