---

- hosts: nodes
  vars:
    src_file: "./files/test.json"
    dst_file: "/root/test.json"
    new_labels:
      region: "wholelottafudge"
      other: "if you like"
  tasks:
    - name: "Copy some 'local facts' to the server"
      copy:
        src: "{{ src_file }}"
        dest: "{{ dst_file }}"
    - name: "Slurp the local fact cache"
      slurp:
        path: "{{ dst_file }}"
      register: slurped
    - name: "Give slurped local facts a nice name"
      set_fact:
        local_fact_cache: "{{ slurped.content | b64decode }}"
    - name: "Update local fact cache on server"
      set_fact:
        local_fact_cache: >
          {{ local_fact_cache |
             combine({'node': {'labels': new_labels }}, recursive=True)}}
    - name: "Check that the fact update succeeded"
      debug:
        msg: "{{ local_fact_cache.node.labels.region }}"
    - name: "Dump the new facts into the local fact cache file"
      copy:
        content: "{{ local_fact_cache }}"
        dest: "{{ dst_file }}"
    - name: "Verify new labels fact value is set"
      shell: "cat {{ dst_file }}"
      register: output
    - debug:
        msg: "{{ output }}"
    - name: "Remove 'fact cache' file "
      file:
        path: "{{ dst_file }}"
        state: absent
