---

- hosts: nodes
  vars:
    src_file: "./files/test.json"
    dst_file: "/root/test.json"
    make_it_fudge: "wholelottafudge"
  tasks:
    - name: "Copy some 'local facts' to the server"
      copy:
        src: "{{ src_file }}"
        dest: "{{ dst_file }}"
    - name: "Slurp the local fact cache"
      slurp:
        path: "{{ dst_file }}"
      register: slurped
    - name: "Give slurped local facts a nice name"
      set_fact:
        local_fact_cache: "{{ slurped.content | b64decode }}"
    - name: "Update local fact cache on server"
      set_fact:
        local_fact_cache: >
          {{ local_fact_cache |
             combine({'node': {'labels': {'region': make_it_fudge }}},
             recursive=True)}}
    - name: "Check that the fact update succeeded"
      debug:
        msg: "{{ local_fact_cache.node.labels.region }}"
    - name: "Dump the new facts into the local fact cache file"
      copy:
        content: "{{ local_fact_cache }}"
        dest: "{{ dst_file }}"
    - name: "Verify that '{{ make_it_fudge }}' fact value is set"
      shell: >
        grep {{ make_it_fudge }} {{ dst_file }}
      register: output
    - name: "FAIL When the fudge is missing"
      fail:
        msg: "'{{ make_it_fudge }}' did not appear in the '{{ dst_file }}'"
      when: output.rc != 0
    - name: "Remove 'fact cache' file "
      file:
        path: "{{ dst_file }}"
        state: absent
