---

- hosts: nodes
  vars:
    src_file: "./files/test.yaml"
    dst_file: "/root/test.yaml"
    new_node_labels:
        region: "infra"
  tasks:
    - name: "Copy some 'local facts' to the server"
      copy:
        src: "{{ src_file }}"
        dest: "{{ dst_file }}"
    - name: "Slurp the local fact cache"
      slurp:
        path: "{{ dst_file }}"
      register: slurped
    - name: "Get node config"
      set_fact:
        node_config: "{{ slurped.content | b64decode | from_yaml }}"
    - set_fact:
        old_node_label_list: |
            {{ node_config.kubeletArguments['node-labels'] }}
    - set_fact:
        old_node_labels_dict: |
          {%- set d = {} -%}
          {%- for x in old_node_label_list -%}
            {%- set k, v = x.split('=') -%}
            {%- set ignore = d.update({ k: v }) -%}
          {%- endfor -%}
          {{ d }}
    - set_fact:
        new_node_labels_dict: |
          {{ old_node_labels_dict | combine(new_node_labels, recursive=True) }}
    - set_fact:
        new_node_labels_list: |
          {%- set l = [] -%}
          {%- for k, v in new_node_labels_dict.iteritems() -%}
            {%- set ignore = l.append(k + '=' + v) -%}
          {%- endfor -%}
          {{ l }}
    - name: "Patch node config"
      set_fact:
        node_config: |
          {{ node_config | combine(
             {'kubeletArguments': {'node-labels': new_node_labels_list}},
               recursive=True
          )}}
    - debug:
        msg: "{{ node_config }}"
    - name: "Dump the new facts into the local fact cache file"
      copy:
        content: "{{ node_config | to_nice_yaml(indent=2) }}"
        dest: "{{ dst_file }}"
    - name: "Verify new labels fact value is set"
      shell: "cat {{ dst_file }}"
      register: output
    - debug:
        msg: "{{ output }}"
    - name: "Remove 'fact cache' file "
      file:
        path: "{{ dst_file }}"
        state: absent
