---

# >> yum install passwordstore
# >> gpg --list-keys
# >> pass init 331763AB
# >> pass insert test/xxx
# >> cat ~/.password-store/test/xxx.gpg

- name: "Test"
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
      some_password: "{{ lookup('passwordstore', 'test/xxx') }}"
  tasks:
      - debug:
          msg: "{{ some_password }}"
