---

- hosts: node2
  tasks:
    - name: "Create a file"
      copy:
        content: "Bigger and Fudgier!!"
        dest: "/etc/fudge2"

- hosts: nodes
  vars:
    remote_copy: "/etc/fudge2"
  tasks:
    - name: "Check for '{{ remote_copy }}' on '{{ inventory_hostname }}'"
      stat:
        path: "{{ remote_copy }}"
      register: ca_file
    - name: "Set has_file flag"
      set_fact:
        has_file: "{{ ca_file.stat.exists }}"
    - name: "Initialize host list"
      set_fact:
        missing: []
    - name: "Figure out which hosts are missing '{{ remote_copy }}'"
      set_fact:
        missing: "{{ missing|default([]) }} + ['{{ item }}']"
      when: not hostvars[item].has_file
      with_items: "{{ groups['nodes'] }}"
    - block:
      - name: "Slurping on '{{ inventory_hostname }}', it has the file"
        slurp:
          path: "{{ remote_copy }}"
        register: slurped
      - name: "Copy temp file over"
        copy:
          content: "{{ slurped.content|b64decode }}"
          dest: "{{ remote_copy }}"
        delegate_to: "{{ item }}"
        with_items: "{{ missing }}"
      when: missing and has_file
  post_tasks:
    - name: "Check for '{{ remote_copy }}' on '{{ inventory_hostname }}'"
      stat:
        path: "{{ remote_copy }}"
      register: the_file
    - debug:
        msg: "Do I exist on {{ inventory_hostname }} = {{ the_file.stat.exists }}"
- hosts: node1,node3
  tasks:
    - name: "Remove file"
      file:
        path: "/etc/fudge2"
        state: absent
